"use client";

import { useState, useEffect } from "react";
import { fetchIdeas, fetchIdea } from "@/lib/api";
import type { IdeaSummary, IdeaResponse } from "@/lib/api";

export default function IdeasPage() {
  const [ideas, setIdeas] = useState<IdeaSummary[]>([]);
  const [selected, setSelected] = useState<IdeaResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchIdeas()
      .then(setIdeas)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  const handleSelect = async (id: string) => {
    try {
      const idea = await fetchIdea(id);
      setSelected(idea);
    } catch (err: any) {
      setError(err.message);
    }
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-2">Generated Ideas</h1>
      <p className="text-zinc-500 mb-8">
        Browse all micro-SaaS proposals generated by the IdeaForge pipeline.
      </p>

      {error && (
        <div className="mb-6 p-4 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-300">
          {error}
        </div>
      )}

      {loading && (
        <div className="flex items-center gap-3 text-zinc-500 py-12">
          <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          Loading ideas...
        </div>
      )}

      {!loading && ideas.length === 0 && !error && (
        <div className="text-center py-16 border border-dashed border-zinc-300 dark:border-zinc-700 rounded-xl">
          <p className="text-zinc-500 mb-4">No ideas generated yet.</p>
          <a
            href="/"
            className="text-sm font-medium text-zinc-900 dark:text-zinc-100 hover:underline"
          >
            Generate your first ideas &rarr;
          </a>
        </div>
      )}

      {!loading && ideas.length > 0 && (
        <div className="grid gap-4">
          {ideas.map((idea) => (
            <button
              key={idea.id}
              onClick={() => handleSelect(idea.id)}
              className={`w-full text-left p-5 rounded-xl border transition-colors ${
                selected?.id === idea.id
                  ? "border-zinc-900 dark:border-zinc-100 bg-zinc-50 dark:bg-zinc-900"
                  : "border-zinc-200 dark:border-zinc-800 hover:border-zinc-400 dark:hover:border-zinc-600 bg-white dark:bg-zinc-950"
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-medium px-2.5 py-1 rounded-full bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400">
                  {idea.niche}
                </span>
                <span className="text-xs text-zinc-400">
                  {new Date(idea.created_at).toLocaleDateString()}
                </span>
              </div>
              <p className="text-sm text-zinc-600 dark:text-zinc-400 line-clamp-2">
                {idea.preview}
              </p>
            </button>
          ))}
        </div>
      )}

      {/* Selected idea detail */}
      {selected && (
        <div className="mt-8 rounded-xl border border-zinc-200 dark:border-zinc-800 overflow-hidden">
          <div className="bg-zinc-100 dark:bg-zinc-800 px-6 py-4 flex items-center justify-between">
            <div>
              <span className="text-xs font-medium px-2.5 py-1 rounded-full bg-zinc-200 dark:bg-zinc-700">
                {selected.niche}
              </span>
              <span className="ml-3 text-sm text-zinc-500">ID: {selected.id}</span>
            </div>
            <button
              onClick={() => setSelected(null)}
              className="text-sm text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100"
            >
              Close
            </button>
          </div>
          <div className="p-6 bg-white dark:bg-zinc-950 max-h-[800px] overflow-y-auto">
            <pre className="whitespace-pre-wrap font-mono text-sm leading-relaxed">
              {selected.content}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}
